name: Commits Version Increase
on:
  push:
    branches:
      - '*'
      - '!master'
jobs:
  version:
    name: Create new patch version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
      - run: |
          git config user.name xaikodev
          git config user.email xaikodev@gmail.com
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Create new patch version
        run: npm version patch
        
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.1


      - name: Push new version tag to repository
        run: git push origin ${{ github.ref_name }} --tags
