name: Minor Increase
on:
  pull_request:
    branches:
      - main

jobs:
  version:
    name: Create new minor version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - run: |
          git config user.name xaikodev
          git config user.email xaikodev@gmail.com
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Create new minor version
        run: npm version minor

      - name: Push new version tag to repository
        run: git push origin main --tags
